version: "3.8"
services:
  anythink-backend-node:
    build: ./backend
    container_name: anythink-backend-node
    command: sh -c "cd backend && yarn install && /wait-for-it.sh mongodb-node:27017 -q -t 60 && yarn dev"

    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb-node:27017/anythink-market
      - GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN=${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}
    working_dir: /usr/src
    volumes:
      - ./:/usr/src/
      - /usr/src/backend/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - "mongodb-node"

  anythink-frontend-react:
    build: ./frontend
    container_name: anythink-frontend-react
    command: sh -c "cd frontend && yarn install && /wait-for-it.sh anythink-backend-node:3000 -t 120 --strict -- curl --head -X GET --retry 30 --retry-connrefused --retry-delay 1 anythink-backend-node:3000/api/ping && yarn start"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - REACT_APP_BACKEND_URL=${CODESPACE_BACKEND_URL:-http://localhost:3000}
      - WDS_SOCKET_PORT=${CODESPACE_WDS_SOCKET_PORT:-3001}
    working_dir: /usr/src
    volumes:
      - ./:/usr/src/
      - /usr/src/frontend/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - "anythink-backend-node"

  mongodb-node:
    container_name: mongodb-node
    restart: always
    image: mongo
    logging:
      driver: none
    volumes:
      - ~/mongo/data:/data/db
    ports:
      - '27017:27017'

  anythink-ack:
    image: public.ecr.aws/v0a2l7y2/wilco/anythink-ack:latest
    container_name: anythink-ack
    environment:
      - GITHUB_TOKEN=$GITHUB_TOKEN
      - CODESPACE_NAME=$CODESPACE_NAME
    depends_on:
      - "anythink-frontend-react" 

  web:
    build: .
    container_name: anythink-web
    ports:
      - "3000:3000"
    volumes:
      - ./:/src
    depends_on:
      - "anythink-backend-node"
    # Optional: Set environment variables for development
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb-node:27017/anythink-market
    # Optional: Command to run your development server (adjust as needed)
    develop:
      watch:
        # Action to perform: 'sync' for hot-reloading code changes
        - action: sync
          path: ./web # Local path to watch
          target: /src/web # Corresponding path in the container
          ignore:
            - node_modules/ # Optional: Paths to ignore
        # Action to perform: 'rebuild' for dependency/config changes
        - action: rebuild
          path: package.json # Watch a specific file for rebuild trigger
    command: npm start # This command should ideally enable live reload within your app

